version: '3'
services:
    hmaster:
        image: ilpan/apache-hbase
        container_name: hbase-master
        volumes:
            # 映射 hdfs 文件目录
            - /data/hadoop/master:/data/hadoop
            # 映射配置文件
            - ../conf:/usr/local/.jenv/candidates/hbase/current/conf
        ports:
            # hdfs nn
            - "50070:50070"
            # yarn rm
            - "8088:8088"
            - "8042"
            # hbase 相关端口映射
            - "16000"
            - "16020"
            - "16010:16010"
            - "16030:16030"
        hostname: hadoop-master
        networks:
            cluster-network:
                aliases:
                    - hadoop-master
        depends_on:
            - hregionserver1
            - hregionserver2
            - hregionserver3
    hregionserver1:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver1
        volumes:
            - /data/hadoop/slave1:/data/hadoop
            - ../conf:/usr/local/.jenv/candidates/hbase/current/conf
        ports:
            # hdfs dn
            - "50075"
            # for yarn
            - "8042"
            # hbase 相关端口随机映射
            - "16000"
            - "16020"
            - "16010"
            - "16030"
        hostname: hadoop-slave1
        networks:
            cluster-network:
                aliases:
                    - hadoop-slave1
    hregionserver2:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver2
        volumes:
            - /data/hadoop/slave2/data:/data/hadoop
            - ../conf:/usr/local/.jenv/candidates/hbase/current/conf
        ports:
            - "50075"
            - "8042"
            - "16000"
            - "16020"
            - "16010"
            - "16030"
        hostname: hadoop-slave2
        networks:
            cluster-network:
                aliases:
                    - hadoop-slave2
    hregionserver3:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver3
        volumes:
            - /data/hadoop/slave3:/data/hadoop
            - ../conf:/usr/local/.jenv/candidates/hbase/current/conf
        ports:
            - "50075"
            - "8042"
            - "16000"
            - "16020"
            - "16010"
            - "16030"
        hostname: hadoop-slave3
        networks:
            cluster-network:
                aliases:
                    - hadoop-slave3

networks:
    cluster-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.88.0.0/16
