version: '3'
services:
    hmaster:
        image: ilpan/apache-hbase
        container_name: hbase-master
        command: "sudo /usr/sbin/sshd -D"
        tty: true
        stdin_open: true
        volumes:
            # 映射 hdfs 文件目录
            # /data/hadoop-master/data/hadoop/zookeeper:/data/hadoop/zookeeper
            - /data/hadoop-master/data:/data/
        ports:
            # hadoop 相关端口映射
            - "50070:50070"
            - "8088:8088"
            # hbase 相关端口映射
            - "16010:16010"
            - "16030:16030"
        hostname: hadoop-master
        extra_hosts:
            - "hadoop-slave1: 172.19.0.11"
            - "hadoop-slave2: 172.19.0.12"
            - "hadoop-slave3: 172.19.0.13"
        networks:
            hbase-network:
                ipv4_address: 172.19.0.10
                aliases:
                    - hmaster
        depends_on:
            - hregionserver1
            - hregionserver2
            - hregionserver3
    hregionserver1:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver1
        command: "sudo /usr/sbin/sshd -D"
        tty: true
        stdin_open: true
        volumes:
            # 映射 hdfs 文件目录
            - /data/hadoop-slave1/data:/data/
        ports:
            # hbase 相关端口随机映射
            - "16010"
            - "16030"
        hostname: hadoop-slave1
        extra_hosts:
            - "hadoop-master: 172.19.0.10"
            - "hadoop-slave2: 172.19.0.12"
            - "hadoop-slave3: 172.19.0.13"
        networks:
            hbase-network:
                ipv4_address: 172.19.0.11
                aliases:
                    - hregionserver1
    hregionserver2:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver2
        command: "sudo /usr/sbin/sshd -D"
        tty: true
        stdin_open: true
        volumes:
            - /data/hadoop-slave2/data:/data/
        ports:
            - "16010"
            - "16030"
        hostname: hadoop-slave2
        extra_hosts:
            - "hadoop-master: 172.19.0.10"
            - "hadoop-slave1: 172.19.0.11"
            - "hadoop-slave3: 172.19.0.13"
        networks:
            hbase-network:
                ipv4_address: 172.19.0.12
                aliases:
                    - hregionserver2
    hregionserver3:
        image: ilpan/apache-hbase
        container_name: hbase-regionserver3
        command: "sudo /usr/sbin/sshd -D"
        tty: true
        stdin_open: true
        volumes:
            - /data/hadoop-slave3/data:/data
        ports:
            - "16010"
            - "16030"
        hostname: hadoop-slave3
        extra_hosts:
            - "hadoop-master: 172.19.0.10"
            - "hadoop-slave1: 172.19.0.11"
            - "hadoop-slave2: 172.19.0.12"
        networks:
            hbase-network:
                ipv4_address: 172.19.0.13
                aliases:
                    - hregionserver3
networks:
    hbase-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.19.0.0/24
