# apache spark

FROM ilpan/base-hadoop
MAINTAINER ilpan<pna110@126.com>

ENV CANDIDATES_HOME /usr/local/.jenv/candidates
ENV SPARK_HOME $SOURCE_HOME/spark/current/

RUN cd /tmp && \
        wget -c http://mirrors.hust.edu.cn/apache/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz && \
        wget -c https://downloads.lightbend.com/scala/2.12.3/scala-2.12.3.tgz && \
        mkdir $SOURCE_HOME/spark $SOURCE_HOME/scala && \
        tar -xzf spark-2.2.0-bin-hadoop2.7.tgz -C $SOURCE_HOME/spark/ && \
        tar -xzf scala-2.12.3.tgz -C $SOURCE_HOME/scala/ && \
        cd $SOURCE_HOME && mv ./spark/spark-2.2.0-bin-hadoop2.7 ./spark/2.2.0-hadoop2.7 && mv ./scala/scala-2.12.3 ./scala/2.12.3 && \
        source "/root/.jenv/bin/jenv-init.sh" && \
        jenv default spark 2.2.0-hadoop2.7 && \
        jenv default scala 2.12.3 && \
        rm -rf /tmp/*

COPY ./conf/slaves $SPARK_HOME/conf/
COPY ./conf/spark-env.sh $SPARK_HOME/conf/

# update hosts which can be changed if you want
COPY ./sh/update-hosts.sh ./
RUN ["/bin/bash", "-c", "./update-hosts.sh"]

EXPOSE 8080 7077 4040

